@extends('base.phtml')
<div class="container">
    <table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nom</th>
            <th scope="col">Prenom</th>
            <th scope="col">Email</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
    <?php $i = 0;?>
    <?php foreach ($this->get('employees') as $row): ?>
        <?php $i++ ?>
        <tr>    
            <th scope="row"><?= $i ?></th>
            <td><?= $row->FirstName ?></td>
            <td><?= $row->LastName ?></td>
            <td><?= $row->EmailAddress ?></td>
            <td>
                <button type="button" class="btn btn-primary"><i class="fas fa-eye"></i></button>
                <button type="button" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                <button type="button" class="btn btn-success"><i class="fas fa-edit"></i></button>
            </td>
        </tr>
    <?php endforeach; ?>
        
        
    </tbody>
    </table>
</div>
